spring:
  profiles:
    default: dev

## 开发环境 配置
#server:
#  address: 0.0.0.0
#  port: 28004
#  servlet:
#    context-path: /api
#
## Spring 配置
#spring:
#  application:
#    name: starsapi-interfaces
#  # 默认 dev 环境
#  #  profiles:
#  #    active: dev
#  config:
#    activate:
#      on-profile:
#        - dev
#  # Redis 配置
#  # todo 需替换配置，然后取消注释
#  redis:
#    # 开发环境-腾讯云服务器-Redis地址
#    host: 123.207.1.38
#    port: 6379
#    database: 2
#    timeout: 5000
#    password:
