spring:
  profiles:
    default: dev

## 开发环境 配置
#server:
#  address: 0.0.0.0
#  port: 28000
#  servlet:
#    context-path: /api
##    # cookie 30 天过期
##    session:
##      cookie:
##        max-age: 2592000
##        # 线上环境-腾讯云服务器-外网地址
##        domain: 123.207.1.38
#
## Spring 配置
#spring:
#  application:
#    name: starsapi-backend
#  # 默认 dev 环境
#  #  profiles:
#  #    active: dev
#  config:
#    activate:
#      on-profile:
#        - dev
#  # 支持 Swagger3
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  # Session 配置
#  session:
#    # todo 取消注释开启分布式 session(须先配置 Redis)
#    store-type: redis
#    # 30 天过期
#    timeout: 2592000
#  # DataSource 配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 开发环境-本地地址-MySQL地址
#    url: jdbc:mysql://localhost:3306/starsapi
#    username:
#    password:
#  # Redis 配置
#  # todo 需替换配置，然后取消注释
#  redis:
#    # 开发环境-腾讯云服务器-Redis地址
#    host: 123.207.1.38
#    port: 6379
#    database: 1
#    timeout: 5000
#    password:
#  # RabbitMQ 配置
#  rabbitmq:
#    # 开发环境-腾讯云服务器-RabbitMQ地址
#    host: 123.207.1.38
#    port: 5672
#    virtual-host: /
#    username: root
#    password:
#
## MybatisPlus 配置
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#
## Dubbo 配置
#dubbo:
#  application:
#    name: starsapi
#    qos:
#      # 是否启动QoS
#      enable: true
#      # 启动QoS绑定的端口
#      port: 28010
#      # 是否允许远程访问
#      foregin:
#        ip: true
#  protocol:
#    name: dubbo
#    port: 28011
#  registry:
#    id: nacos-registry
#    # 开发环境-本地地址-Nacos地址
#    address: nacos://localhost:8848
#    # 线上环境-腾讯云服务器内网地址-Nacos地址
##    address: nacos://localhost:8848
#
## 对象存储 配置
## todo 需替换配置
#aliyun:
#  oss:
#    endpoint: oss-cn-guangzhou.aliyuncs.com
#    urlPrefix: http://stars.oss-cn-guangzhou.aliyuncs.com
#    accessKeyId:
#    accessKeySecret:
#    bucketName: stars
#    fileHost: files
